schools:
   path: /schools
   controller: App\Controller\SchoolController::findAllSchools

createSchool:
   path: /school/create
   controller: App\Controller\SchoolController::createSchool
#lo colocamos debajo porque sino toma create como el id
schoolById:
   path: /school/{id}
   controller: App\Controller\SchoolController::schoolById

deleteSchool:
   path: /school/delete/{id}
   controller: App\Controller\SchoolController::deleteSchool
   
updateSchool:
   path: /school/update/{id}
   controller: App\Controller\SchoolController::updateSchool